baseURL = 'https://kevinnfeng.github.io/'
title = "Kevin's Blog"
theme = "PaperMod"

[params]
  comments = true
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.giscus]
    repo = "Kevinnfeng/Kevinnfeng.github.io"
    repoId = "R_kgDOTDjkGQ"
    category = "Announcements"
    categoryId = "DIC_kwDOTDjkGc4C_x6C"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
    lang = "en"
